version: "3.8"

services:
  data_scrape_binance_us:
    build:
      context: .  # Points to the directory containing the Dockerfile
      dockerfile: Dockerfile
    image: algos:latest
    network_mode: bridge
    env_file:
      - /home/paul/src/algos/.env
    restart: always
    command: python3.10 -u data_trade_scraper.py --exchange binance_us

  data_scrape_kraken:
    build:
      context: .  # Ensures consistency in build context
      dockerfile: Dockerfile
    image: algos:latest  # Reuse the same image for consistency
    network_mode: bridge
    env_file:
      - /home/paul/src/algos/.env
    restart: always
    command: python3.10 -u data_trade_scraper.py --exchange kraken

  trading_summary:
    build:
      context: .  # Ensures consistency in build context
      dockerfile: Dockerfile
    image: algos:latest  # Reuse the same image for consistency
    network_mode: bridge
    env_file:
      - /home/paul/src/algos/.env
    restart: always
    command: python3.10 -u update_trading_summary.py

  # live_framework: 
  #   build:
  #     context: .  # Ensures consistency in build context
  #     dockerfile: Dockerfile
  #   image: algos:latest  # Reuse the same image for consistency
  #   network_mode: bridge
  #   env_file:
  #     - /home/paul/src/algos/.env
  #   restart: always
  #   command: python3.10 -u live_framework_v2.py --port simple_stochastic_1


  # ### TODO: get these up 
  # ##
  # #
  # data_update_signal:
  #   <<: *base
  #   command: python -u update_signal.py  # --signal_name btc_sig_1

  # live_framework: 
  #   <<: *base 
  #   command: python -u live_framework_v2.py # --signal_name 

  # # ### want to replace this functionality 
  # #
  # #
  # filebeat:
  #   image: elastic/filebeat:8.2.2
  #   volumes:d
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker:/var/lib/docker
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
  #   depends_on:
  #     - logstash
  #   command: -strict.perms=false
  #   user: root

  # logstash:
  #   image: opensearchproject/logstash-oss-with-opensearch-output-plugin
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/conf/logstash.conf
  #   command: ["-f", "/usr/share/logstash/conf/logstash.conf"]
  #   user: root